In [95]:
# Music Recommendor Engine for online Music store
# User signs up .. enters age, gender
# The recommendor engine looks at the profile of user & recommends Music albums for selling
# Using Machine Learning to increase Sales
# Uses data of existing users... to recommend music for new users
# Create a Model .. feed data of existing users.. recognize patterns of the data
# When a new user signs up .. Model will recommend suggestions & make predictions
# Model will recommend Music genres for new user based on his/her profile

In [96]:
# STEPS :-
# 1. Import Data
# 2. Clean/Sanitize the data
# 3. Split data into training set & test set
# 4. Select ML algorithm to build a Model
# 5. Train the Model to make predictions using training set & test set data
# 6. Evaluate the result & improve/refine the Model or change the algorithm

In [97]:
import pandas as pd

readcsv = pd.read_csv("D:\\Downloads Chrome\\music.csv") # returns dataframe object

readcsv

age   gender       genre
0    20        1      HipHop
1    23        1      HipHop
2    25        1      HipHop
3    26        1        Jazz
4    29        1        Jazz
5    30        1        Jazz
6    31        1   Classical
7    33        1   Classical
8    37        1   Classical
9    20        0       Dance
10   21        0       Dance
11   25        0       Dance
12   26        0    Acoustic
13   27        0    Acoustic
14   30        0    Acoustic
15   31        0   Classical
16   34        0   Classical
17   35        0   Classical

In [98]:
readcsv.describe

<bound method NDFrame.describe of     age   gender       genre
0    20        1      HipHop
1    23        1      HipHop
2    25        1      HipHop
3    26        1        Jazz
4    29        1        Jazz
5    30        1        Jazz
6    31        1   Classical
7    33        1   Classical
8    37        1   Classical
9    20        0       Dance
10   21        0       Dance
11   25        0       Dance
12   26        0    Acoustic
13   27        0    Acoustic
14   30        0    Acoustic
15   31        0   Classical
16   34        0   Classical
17   35        0   Classical>

In [99]:
readcsv.values

array([[20, 1, ' HipHop'],
       [23, 1, ' HipHop'],
       [25, 1, ' HipHop'],
       [26, 1, ' Jazz'],
       [29, 1, ' Jazz'],
       [30, 1, ' Jazz'],
       [31, 1, ' Classical'],
       [33, 1, ' Classical'],
       [37, 1, ' Classical'],
       [20, 0, ' Dance'],
       [21, 0, ' Dance'],
       [25, 0, ' Dance'],
       [26, 0, ' Acoustic'],
       [27, 0, ' Acoustic'],
       [30, 0, ' Acoustic'],
       [31, 0, ' Classical'],
       [34, 0, ' Classical'],
       [35, 0, ' Classical']], dtype=object)

In [100]:
readcsv.shape

(18, 3)

In [101]:
readcsv.describe()

age     gender
count  18.000000  18.000000
mean   27.944444   0.500000
std     5.127460   0.514496
min    20.000000   0.000000
25%    25.000000   0.000000
50%    28.000000   0.500000
75%    31.000000   1.000000
max    37.000000   1.000000

In [102]:
readcsv.dtypes

age         int64
 gender     int64
 genre     object
dtype: object

In [103]:
readcsv.to_numpy()

array([[20, 1, ' HipHop'],
       [23, 1, ' HipHop'],
       [25, 1, ' HipHop'],
       [26, 1, ' Jazz'],
       [29, 1, ' Jazz'],
       [30, 1, ' Jazz'],
       [31, 1, ' Classical'],
       [33, 1, ' Classical'],
       [37, 1, ' Classical'],
       [20, 0, ' Dance'],
       [21, 0, ' Dance'],
       [25, 0, ' Dance'],
       [26, 0, ' Acoustic'],
       [27, 0, ' Acoustic'],
       [30, 0, ' Acoustic'],
       [31, 0, ' Classical'],
       [34, 0, ' Classical'],
       [35, 0, ' Classical']], dtype=object)

In [104]:
readcsv.values

array([[20, 1, ' HipHop'],
       [23, 1, ' HipHop'],
       [25, 1, ' HipHop'],
       [26, 1, ' Jazz'],
       [29, 1, ' Jazz'],
       [30, 1, ' Jazz'],
       [31, 1, ' Classical'],
       [33, 1, ' Classical'],
       [37, 1, ' Classical'],
       [20, 0, ' Dance'],
       [21, 0, ' Dance'],
       [25, 0, ' Dance'],
       [26, 0, ' Acoustic'],
       [27, 0, ' Acoustic'],
       [30, 0, ' Acoustic'],
       [31, 0, ' Classical'],
       [34, 0, ' Classical'],
       [35, 0, ' Classical']], dtype=object)

In [105]:
readcsv.index

RangeIndex(start=0, stop=18, step=1)

In [106]:
readcsv.head

<bound method NDFrame.head of     age   gender       genre
0    20        1      HipHop
1    23        1      HipHop
2    25        1      HipHop
3    26        1        Jazz
4    29        1        Jazz
5    30        1        Jazz
6    31        1   Classical
7    33        1   Classical
8    37        1   Classical
9    20        0       Dance
10   21        0       Dance
11   25        0       Dance
12   26        0    Acoustic
13   27        0    Acoustic
14   30        0    Acoustic
15   31        0   Classical
16   34        0   Classical
17   35        0   Classical>

In [107]:
readcsv.columns

Index(['age', ' gender', ' genre'], dtype='object')

In [108]:
readcsv.abs

<bound method NDFrame.abs of     age   gender       genre
0    20        1      HipHop
1    23        1      HipHop
2    25        1      HipHop
3    26        1        Jazz
4    29        1        Jazz
5    30        1        Jazz
6    31        1   Classical
7    33        1   Classical
8    37        1   Classical
9    20        0       Dance
10   21        0       Dance
11   25        0       Dance
12   26        0    Acoustic
13   27        0    Acoustic
14   30        0    Acoustic
15   31        0   Classical
16   34        0   Classical
17   35        0   Classical>

In [109]:
readcsv.lookup

<bound method DataFrame.lookup of     age   gender       genre
0    20        1      HipHop
1    23        1      HipHop
2    25        1      HipHop
3    26        1        Jazz
4    29        1        Jazz
5    30        1        Jazz
6    31        1   Classical
7    33        1   Classical
8    37        1   Classical
9    20        0       Dance
10   21        0       Dance
11   25        0       Dance
12   26        0    Acoustic
13   27        0    Acoustic
14   30        0    Acoustic
15   31        0   Classical
16   34        0   Classical
17   35        0   Classical>

In [110]:
# Now let us inspect the data-frame object (readcsv .. make sure the data is loaded properly

readcsv

age   gender       genre
0    20        1      HipHop
1    23        1      HipHop
2    25        1      HipHop
3    26        1        Jazz
4    29        1        Jazz
5    30        1        Jazz
6    31        1   Classical
7    33        1   Classical
8    37        1   Classical
9    20        0       Dance
10   21        0       Dance
11   25        0       Dance
12   26        0    Acoustic
13   27        0    Acoustic
14   30        0    Acoustic
15   31        0   Classical
16   34        0   Classical
17   35        0   Classical

In [111]:
# Now let us prepare the data-frame i.e clean it up i.e remove duplicates, remove null values etc
# Since current csv data does not have any duplicates, nulls.. so we don't need to prepare it

# Let us Split this data-set into 2 separate data-sets... INPUT SET & OUTPUT SET 
# Here, the Age & Gender would be INPUT set.. the Genre would be OUTPUT set
# Age, Gender would be the input to the Model.. to predict the OUTPUT i.e Genre
# Training any Model .. requires 2 sets .. INPUT set & OUTPUT set
# Model would be trained to predict the OUTPUT set after receiving INPUT set

In [112]:
 #X= readcsv.drop("genre", axis=1, inplace=True)
# X

In [115]:
#X = readcsv.drop(columns=['genre'], axis=1)

In [116]:
Y = readcsv['genre']
Y

KeyError: 'genre'